spring:
  application:
    name: LingoCraft
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: ${db.driver}
  jooq:
    sql-dialect = postgres

db:
  url: jdbc:postgresql://localhost:6432/lingo_craft
  username: lingo_owner
  password: lingo_owner
  driver: org.postgresql.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 37245
