spring:
  application:
    name: LingoCraft
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:26257/${DATABASE_NAME:onboarding}${DATABASE_CONNECTION_PARAMS:}
    username: onb_user
    password: ${DATABASE_PASSWORD:""}
    driver-class-name: ${db.driver}
  jooq:
    sql-dialect = postgres

db:
  url: jdbc:postgresql://localhost:5432/lingo_craft
  username: postgres
  password: Admin123
  driver: org.postgresql.Driver

#db:
#  url: jdbc:postgresql://localhost:6432/lingo_craft
#  username: lingo_owner
#  password: lingo_owner
#  driver: org.postgresql.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 37245
