spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: LingoCraft
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: ${db.driver}
  jooq:
    sql-dialect = postgres
  temporal:
    namespace: default
    connection:
      target: 127.0.0.1:7233
    workersAutoDiscovery:
      packages: com.lingo.craft

db:
  url: jdbc:postgresql://localhost:5432/lingo_craft
  username: postgres
  password: postgres
  driver: org.postgresql.Driver

server:
  port: 37245

workflows:
  contentAnalysisEventWorkflow:
    workflowIdPrefix: CONTENT_PROCESSING_WORKFLOW_

deepl:
  allowTranslation: true
  apiKey: 97e14aba-f53c-4d07-8ef2-009f670e7652:fx

stanfordCore:
  annotators: "tokenize, ssplit, parse, sentiment"

activities:
  contentSentimentAnalysisPersistence:
    startToCloseTimeout: 120s
    initialInterval: 1s
    maximumAttempts: 2
    backoffCoefficient: 5.0
    maximumInterval: 1h

  contentTranslation:
    startToCloseTimeout: 120s
    initialInterval: 1s
    maximumAttempts: 3
    backoffCoefficient: 5.0
    maximumInterval: 10m

  contentSemanticAnalysis:
    startToCloseTimeout: 60s
    initialInterval: 1s
    maximumAttempts: 0 # unlimited
    backoffCoefficient: 5.0
    maximumInterval: 1h
