### Detect language
POST {{host}}/analysis
Content-Type: application/json

{
  "text": "Chaque matin, je me réveillais avec la douce lueur du soleil.",
  "userId": "6980ed44-4a7f-4b6d-81f0-7eb177c60c1f"
}

### Upload file to detect language
POST {{host}}/analysis/upload?userId=6980ed44-4a7f-4b6d-81f0-7eb177c60c1f
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="example.txt"

< ./files/example.txt

--boundary
