### Detect language
POST {{host}}/analysis
Content-Type: application/json

{
  "text": "This is an excellent product. I bought it yesterday and i liked it so much. It works very well and good quality."
}

### Upload file to detect language
POST {{host}}/analysis/upload
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="example.txt"

< ./files/example.txt

--boundary
