### Detect language
POST {{host}}/detect
Content-Type: application/json

{
  "text": "This is an excellent book. I enjoy reading it. I can read on Sundays. Today is only Tuesday. Can't wait for next Sunday. The working week is unbearably long. It's awful."
}

### Upload file to detect language
POST {{host}}/detect/upload
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="example.txt"

< ./files/example.txt

--boundary
