/*
 * This file is generated by jOOQ.
 */
package com.lingo.craft;


import com.lingo.craft.tables.LanguageAnalysis;
import com.lingo.craft.tables.Role;
import com.lingo.craft.tables.User;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.language_analysis</code>.
     */
    public final LanguageAnalysis LANGUAGE_ANALYSIS = LanguageAnalysis.LANGUAGE_ANALYSIS;

    /**
     * The table <code>public.role</code>.
     */
    public final Role ROLE = Role.ROLE;

    /**
     * The table <code>public.user</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            LanguageAnalysis.LANGUAGE_ANALYSIS,
            Role.ROLE,
            User.USER
        );
    }
}
