/*
 * This file is generated by jOOQ.
 */
package com.lingo.craft;


import com.lingo.craft.tables.Role;
import com.lingo.craft.tables.User;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.role</code>.
     */
    public static final Role ROLE = Role.ROLE;

    /**
     * The table <code>public.user</code>.
     */
    public static final User USER = User.USER;
}
