/*
 * This file is generated by jOOQ.
 */
package com.lingo.craft.main;


import com.lingo.craft.main.tables.User;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.user</code>.
     */
    public static final User USER = User.USER;
}
