/*
 * This file is generated by jOOQ.
 */
package com.lingo.craft.tables.records;


import com.lingo.craft.tables.LanguageAnalysis;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LanguageAnalysisRecord extends UpdatableRecordImpl<LanguageAnalysisRecord> implements Record6<UUID, UUID, Integer, String, String, JSONB> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.language_analysis.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.language_analysis.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.language_analysis.userid</code>.
     */
    public void setUserid(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.language_analysis.userid</code>.
     */
    public UUID getUserid() {
        return (UUID) get(1);
    }

    /**
     * Setter for
     * <code>public.language_analysis.accumulatedcontentsentimentscore</code>.
     */
    public void setAccumulatedcontentsentimentscore(Integer value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>public.language_analysis.accumulatedcontentsentimentscore</code>.
     */
    public Integer getAccumulatedcontentsentimentscore() {
        return (Integer) get(2);
    }

    /**
     * Setter for
     * <code>public.language_analysis.positivesentimentpercentage</code>.
     */
    public void setPositivesentimentpercentage(String value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>public.language_analysis.positivesentimentpercentage</code>.
     */
    public String getPositivesentimentpercentage() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>public.language_analysis.accumulatedcontentsentiment</code>.
     */
    public void setAccumulatedcontentsentiment(String value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>public.language_analysis.accumulatedcontentsentiment</code>.
     */
    public String getAccumulatedcontentsentiment() {
        return (String) get(4);
    }

    /**
     * Setter for
     * <code>public.language_analysis.contentsentimentanalysismodels</code>.
     */
    public void setContentsentimentanalysismodels(JSONB value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>public.language_analysis.contentsentimentanalysismodels</code>.
     */
    public JSONB getContentsentimentanalysismodels() {
        return (JSONB) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<UUID, UUID, Integer, String, String, JSONB> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<UUID, UUID, Integer, String, String, JSONB> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return LanguageAnalysis.LANGUAGE_ANALYSIS.ID;
    }

    @Override
    public Field<UUID> field2() {
        return LanguageAnalysis.LANGUAGE_ANALYSIS.USERID;
    }

    @Override
    public Field<Integer> field3() {
        return LanguageAnalysis.LANGUAGE_ANALYSIS.ACCUMULATEDCONTENTSENTIMENTSCORE;
    }

    @Override
    public Field<String> field4() {
        return LanguageAnalysis.LANGUAGE_ANALYSIS.POSITIVESENTIMENTPERCENTAGE;
    }

    @Override
    public Field<String> field5() {
        return LanguageAnalysis.LANGUAGE_ANALYSIS.ACCUMULATEDCONTENTSENTIMENT;
    }

    @Override
    public Field<JSONB> field6() {
        return LanguageAnalysis.LANGUAGE_ANALYSIS.CONTENTSENTIMENTANALYSISMODELS;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getUserid();
    }

    @Override
    public Integer component3() {
        return getAccumulatedcontentsentimentscore();
    }

    @Override
    public String component4() {
        return getPositivesentimentpercentage();
    }

    @Override
    public String component5() {
        return getAccumulatedcontentsentiment();
    }

    @Override
    public JSONB component6() {
        return getContentsentimentanalysismodels();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getUserid();
    }

    @Override
    public Integer value3() {
        return getAccumulatedcontentsentimentscore();
    }

    @Override
    public String value4() {
        return getPositivesentimentpercentage();
    }

    @Override
    public String value5() {
        return getAccumulatedcontentsentiment();
    }

    @Override
    public JSONB value6() {
        return getContentsentimentanalysismodels();
    }

    @Override
    public LanguageAnalysisRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public LanguageAnalysisRecord value2(UUID value) {
        setUserid(value);
        return this;
    }

    @Override
    public LanguageAnalysisRecord value3(Integer value) {
        setAccumulatedcontentsentimentscore(value);
        return this;
    }

    @Override
    public LanguageAnalysisRecord value4(String value) {
        setPositivesentimentpercentage(value);
        return this;
    }

    @Override
    public LanguageAnalysisRecord value5(String value) {
        setAccumulatedcontentsentiment(value);
        return this;
    }

    @Override
    public LanguageAnalysisRecord value6(JSONB value) {
        setContentsentimentanalysismodels(value);
        return this;
    }

    @Override
    public LanguageAnalysisRecord values(UUID value1, UUID value2, Integer value3, String value4, String value5, JSONB value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LanguageAnalysisRecord
     */
    public LanguageAnalysisRecord() {
        super(LanguageAnalysis.LANGUAGE_ANALYSIS);
    }

    /**
     * Create a detached, initialised LanguageAnalysisRecord
     */
    public LanguageAnalysisRecord(UUID id, UUID userid, Integer accumulatedcontentsentimentscore, String positivesentimentpercentage, String accumulatedcontentsentiment, JSONB contentsentimentanalysismodels) {
        super(LanguageAnalysis.LANGUAGE_ANALYSIS);

        setId(id);
        setUserid(userid);
        setAccumulatedcontentsentimentscore(accumulatedcontentsentimentscore);
        setPositivesentimentpercentage(positivesentimentpercentage);
        setAccumulatedcontentsentiment(accumulatedcontentsentiment);
        setContentsentimentanalysismodels(contentsentimentanalysismodels);
        resetChangedOnNotNull();
    }
}
