/*
 * This file is generated by jOOQ.
 */
package com.lingo.craft.tables.records;


import com.lingo.craft.tables.Role;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoleRecord extends UpdatableRecordImpl<RoleRecord> implements Record3<UUID, String, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.role.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.role.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.role.rolepermissions</code>.
     */
    public void setRolepermissions(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.role.rolepermissions</code>.
     */
    public String getRolepermissions() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.role.userid</code>.
     */
    public void setUserid(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.role.userid</code>.
     */
    public UUID getUserid() {
        return (UUID) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, String, UUID> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<UUID, String, UUID> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Role.ROLE.ID;
    }

    @Override
    public Field<String> field2() {
        return Role.ROLE.ROLEPERMISSIONS;
    }

    @Override
    public Field<UUID> field3() {
        return Role.ROLE.USERID;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getRolepermissions();
    }

    @Override
    public UUID component3() {
        return getUserid();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getRolepermissions();
    }

    @Override
    public UUID value3() {
        return getUserid();
    }

    @Override
    public RoleRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public RoleRecord value2(String value) {
        setRolepermissions(value);
        return this;
    }

    @Override
    public RoleRecord value3(UUID value) {
        setUserid(value);
        return this;
    }

    @Override
    public RoleRecord values(UUID value1, String value2, UUID value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoleRecord
     */
    public RoleRecord() {
        super(Role.ROLE);
    }

    /**
     * Create a detached, initialised RoleRecord
     */
    public RoleRecord(UUID id, String rolepermissions, UUID userid) {
        super(Role.ROLE);

        setId(id);
        setRolepermissions(rolepermissions);
        setUserid(userid);
        resetChangedOnNotNull();
    }
}
