openapi: 3.0.0
info:
  title: Lingo Craft API
  version: 0.0.1
servers:
  - url: /lingo-craft/v1
    description: Lingo Craft APIs
paths:
  /user/{id}:
    get:
      summary: Get a user by its id.
      operationId: getUserById
      description: This endpoint will get an existing user from our system.
      parameters:
        - name: id
          in: path
          required: true
          description: id of existing user
          schema:
            type: string
      responses:
        '200':
          description: Got User by id successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserResponse'

        '400':
          description: Bad request, check request payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      summary: Delete a user by its id.
      operationId: deleteUserById
      description: This endpoint will delete an existing user from our system.
      parameters:
        - name: id
          in: path
          required: true
          description: ID of existing user
          schema:
            type: string
      responses:
        '200':
          description: User deleted successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteUserResponse'
        '400':
          description: Bad request, check request payload.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /user/email/{email}/password/{password}:
    get:
      summary: Get a user by email and password.
      operationId: getUserByEmailPassword
      description: This endpoint will get an existing user from our system.
      parameters:
        - name: email
          in: path
          required: true
          description: email of existing user
          schema:
            type: string
        - name: password
          in: path
          required: true
          description: password of existing user
          schema:
            type: string
      responses:
        '200':
          description: Got User by email and password successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserResponse'

        '400':
          description: Bad request, check request payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /user:
    post:
      summary: Create a new user.
      operationId: createUser
      description: This endpoint will generate a new user in our system.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '200':
          description: New User is created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateUserResponse'

        '400':
          description: Bad request, check request payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /detect:
    post:
      summary: Api to detect language
      operationId: detectLanguage
      description: Api to detect a language against a text provided by user.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LanguageDetectionRequest'
      responses:
        '200':
          description: Language is detected successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LanguageDetectionResponse'

        '400':
          description: Bad request, check request payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /detect/upload:
    post:
      summary: Api to detect language from file
      operationId: detectLanguageFromFile
      description: Upload file with content to detect language
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Language is detected successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LanguageDetectionResponse'

        '400':
          description: Bad request, check request payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    LanguageDetectionRequest:
      type: object
      properties:
        text:
          type: string
          description: A text provided by user to detect its language.
      required:
        - text

    LanguageDetectionResponse:
      allOf:
        - $ref: '#/components/schemas/LanguageDetectionRequest'
        - type: object
          properties:
            languageCode:
              type: string
              description: Language ISO-639 code.
            confidence:
              type: string
              description: Language detection confidence.
              enum:
                - HIGH
                - MEDIUM
                - LOW
                - NONE
            rawScore:
              type: number
              description: Language detection raw score.
          required:
            - languageCode
            - confidence
            - rawScore

    CreateUserRequest:
      type: object
      properties:
        name:
          type: string
          description: Name of new user we are aiming to create.
        password:
          type: string
          description: Password of new user we are aiming to create.
        email:
          type: string
          description: Email of new user we are aiming to create.
        phone:
          type: string
          description: Phone of new user we are aiming to create.
        age:
          type: integer
          description: Age of new user we are aiming to create.
        gender:
          type: string
          description: Gender of new user we are aiming to create.
          enum:
            - MALE
            - FEMALE
        roleId:
          type: integer
          description: RoleId of new user we are aiming to create.
      required:
        - name
        - password
        - email
        - phone
        - age
        - gender
        - roleId

    CreateUserResponse:
      allOf:
        - $ref: '#/components/schemas/CreateUserRequest'
        - type: object
          properties:
            id:
             type: string
             description: Id of newly created user.
          required:
            - id

    GetUserResponse:
      allOf:
        - $ref: '#/components/schemas/CreateUserResponse'

    DeleteUserResponse:
      allOf:
        - $ref: '#/components/schemas/GetUserResponse'

    ErrorResponse:
      type: object
      properties:
        errorMessage:
          type: string
          description: Error message details.